# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[['open', '열림'], ['close', '닫힘']], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
