# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import dojo1.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo1', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voc_type', models.CharField(max_length=20)),
                ('try_nm', models.CharField(max_length=2)),
                ('sgg_nm', models.CharField(max_length=3)),
                ('emd_nm', models.CharField(max_length=5)),
                ('latitute', models.FloatField()),
                ('longitude', models.FloatField()),
                ('occr_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=13, validators=[dojo1.models.validate_phone]),
        ),
    ]
