# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo1', '0004_auto_20180201_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
